### PR TITLE
fix: fix connect error code handling for disabled flags

### LINKED ISSUE #668: [BUG] Disabled flags results in an incorrect error message
### Observed behavior

When feature flag is `DISABLED`, flag return an incorrect error message 

`error code: PROVIDER_NOT_READY: connection not made`

### Expected Behavior

The error message should highlight the fact that flag is disabled. This must be corrected at code level [1]

[1] - https://github.com/open-feature/flagd/blob/main/core/pkg/service/flag-evaluation/flag_evaluator.go#L325C1-L326

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Kavindu-Dodan**
## This PR

fixes #668 

Fixes incorrect error code mapping, which resulted in error message `error code: PROVIDER_NOT_READY: connection not made`

With fix, the error code is set to unknown (as there is no appropriate error code for this error) , and results in message `openfeature: GENERAL: unknown: FLAG_DISABLED`

### CODE REVIEW

File: core/pkg/service/flag-evaluation/flag_evaluator_test.go [hunk 1]
```diff
@@ -903,3 +903,50 @@ func getMetricReader() (*telemetry.MetricsRecorder, metric.Reader) {
 	rs := resource.NewWithAttributes("testSchema")
 	return telemetry.NewOTelRecorder(exp, rs, "testSvc"), exp
 }
+
+// TestFlag_Evaluation_ErrorCodes test validate error mapping from known errors to connect.
+// Code and avoid accidental changes. This is essential as SDK implementations rely on connect.
```
Comment (beeme1mr) [inline core/pkg/service/flag-evaluation/flag_evaluator_test.go:908]: > Code and avoid accidental changes.
What does that mean?

File: core/pkg/service/flag-evaluation/flag_evaluator.go [hunk 2]
```diff
@@ -322,11 +322,9 @@ func errFormat(err error) error {
 		return connect.NewError(connect.CodeNotFound, fmt.Errorf("%s, %s", ErrorPrefix, err.Error()))
 	case model.TypeMismatchErrorCode:
 		return connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("%s, %s", ErrorPrefix, err.Error()))
-	case model.FlagDisabledErrorCode:
-		return connect.NewError(connect.CodeUnavailable, fmt.Errorf("%s, %s", ErrorPrefix, err.Error()))
 	case model.ParseErrorCode:
 		return connect.NewError(connect.CodeDataLoss, fmt.Errorf("%s, %s", ErrorPrefix, err.Error()))
-	case model.GeneralErrorCode:
+	case model.FlagDisabledErrorCode, model.GeneralErrorCode:
```
Comment (beeme1mr) [inline core/pkg/service/flag-evaluation/flag_evaluator.go:327]: You could argue that a disabled flag should behave like it's not there. If that's the case, the `FLAG_NOT_FOUND` error code would be more appropriate. What do you think @toddbaert?

Comment (beeme1mr) [reply core/pkg/service/flag-evaluation/flag_evaluator.go:327]: We could also consider adding a `FLAG_DISABLED` error code but I think that would be a breaking spec change.

Comment (Kavindu-Dodan) [reply core/pkg/service/flag-evaluation/flag_evaluator.go:327]: Good point, I don't have a strong opinion here. I am fine with the current approach (error with FLAG_DISABLED message section) or the proposed change.

Comment (toddbaert) [reply core/pkg/service/flag-evaluation/flag_evaluator.go:327]: Personally I'm of the opinion that flags disabled in flagd should behave EXACTLY as flags that aren't there. Basically they're "unreleased" flags.

File: core/pkg/service/flag-evaluation/flag_evaluator_test.go [hunk 3]
```diff
@@ -903,3 +903,50 @@ func getMetricReader() (*telemetry.MetricsRecorder, metric.Reader) {
...
+// Code to differentiate GRPC errors vs Flag errors. For any change, we must change respective SDK changes
```
Comment (toddbaert) [inline core/pkg/service/flag-evaluation/flag_evaluator_test.go:909]:
```suggestion
// TestFlag_Evaluation_ErrorCodes test validate error mapping from known errors to connect.
// Code and avoid accidental changes. This is essential as provider implementations rely on connect.
// Code to differentiate gRPC errors vs Flag errors. Changes must be absorbed by flagd providers.
```

Comment (toddbaert) [reply core/pkg/service/flag-evaluation/flag_evaluator_test.go:909]: The capitalization here is a bit odd. Maybe a block comment would be better?

Comment (Kavindu-Dodan) [reply core/pkg/service/flag-evaluation/flag_evaluator_test.go]: Fixed with the latest commit. Thank you pointing this out

File: core/pkg/service/flag-evaluation/flag_evaluator.go (hunk 2 above)
Comment (Kavindu-Dodan) [reply core/pkg/service/flag-evaluation/flag_evaluator.go:327]: Reason will be an error and we can do the following, 

At flagd, mark disabled flags with connect `CodeNotFound` with reason (error message) `FLAG_DISABLED`

This from Go SDK will get converted to following error message, 

`openfeature: FLAG_NOT_FOUND: not_found: FlagdError:, FLAG_DISABLED`

cc @beeme1mr  @toddbaert

Comment (Kavindu-Dodan) [reply core/pkg/service/flag-evaluation/flag_evaluator.go]: @toddbaert  thanks and done - updated with the latest commit . Latest error log look like below,

`openfeature: FLAG_NOT_FOUND: not_found: FlagdError:, FLAG_DISABLED`

**Comment by Kavindu-Dodan** [comment]
Latest error message - `openfeature: FLAG_NOT_FOUND: not_found: FlagdError:, FLAG_DISABLED`

**Review by toddbaert — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]
