### PR TITLE
fix: changed eventing configuration mutex to rwmutex and added missing lock

### LINKED ISSUE #219: [BUG] Missing lock in assignment of channel to an event stream request
### Observed behavior

Haven't observed a race condition but it could occur [here](https://github.com/open-feature/flagd/blob/main/pkg/service/connect_service.go#L147).

### Expected Behavior

No race conditions.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by skyerus**
## This PR

Changed eventing configuration mutex to rwmutex and added missing lock.

### Related Issues

Fixes #219

### CODE REVIEW

File: pkg/service/connect_service.go [hunk 1]
```diff
@@ -181,11 +184,11 @@ func (s *ConnectService) EventStream(
 }
 
 func (s *ConnectService) Notify(n Notification) {
-	s.eventingConfiguration.mu.Lock()
+	s.eventingConfiguration.mu.RLock()
```
Comment (skyerus) [inline pkg/service/connect_service.go:187]: Converted to RLock/RUnlock for efficiency.

File: pkg/service/connect_service.go [hunk 2]
```diff
@@ -144,25 +144,29 @@ func (s *ConnectService) EventStream(
...
 	}()
-	s.eventingConfiguration.subs[req] <- Notification{
+	requestNotificationChan <- Notification{
 		Type: ProviderReady,
 	}
+	ticker := time.NewTicker(20 * time.Second)
 	for {
 		select {
-		case <-time.After(20 * time.Second):
+		case <-ticker.C:
```
Comment (skyerus) [inline pkg/service/connect_service.go:162]: I assumed that this is meant to occur every 20 seconds but will remove if I'm wrong. @james-milligan can hopefully shine some light

Comment (james-milligan) [inline pkg/service/connect_service.go]: I believe these have a similar outcome due to the wrapping for loop. Original intention was to keep this as a timeout, as we don need to send a keep alive if either the request is closed, or we send a notification (this is to prevent read/write timeouts)

**Review by james-milligan — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]

File: pkg/service/connect_service.go [hunk 3]
```diff
@@ -181,11 +184,11 @@ func (s *ConnectService) EventStream(
 }
 
 func (s *ConnectService) Notify(n Notification) {
-	s.eventingConfiguration.mu.Lock()
+	s.eventingConfiguration.mu.RLock()
 	for _, send := range s.eventingConfiguration.subs {
 		send <- n
 	}
-	s.eventingConfiguration.mu.Unlock()
+	s.eventingConfiguration.mu.RUnlock()
```
Comment (toddbaert) [inline pkg/service/connect_service.go:191]: Might be better to pull this up and defer it?

**Review by toddbaert — APPROVED** [review]

File: pkg/service/connect_service.go (hunk 3 above)
Comment (skyerus) [reply pkg/service/connect_service.go]: done

**Comment by beeme1mr** [comment]
@AlexsJones, could you please review this when you have a moment?

File: pkg/service/connect_service.go [hunk 4]
```diff
@@ -144,13 +144,16 @@ func (s *ConnectService) EventStream(
 	req *connect.Request[emptypb.Empty],
 	stream *connect.ServerStream[schemaV1.EventStreamResponse],
 ) error {
-	s.eventingConfiguration.subs[req] = make(chan Notification, 1)
+	requestNotificationChan := make(chan Notification, 1)
+	s.eventingConfiguration.mu.Lock()
```
Comment (AlexsJones) [inline pkg/service/connect_service.go:148]: Can we defer this for nicer semantics?

**Comment by AlexsJones** [comment]
I might be wrong here but
```
	requestNotificationChan := make(chan Notification, 1)
	s.eventingConfiguration.mu.Lock()
	s.eventingConfiguration.subs[req] = requestNotificationChan
	s.eventingConfiguration.mu.Unlock()
```

If you have two goroutines calling the `eventStream` function the second will have it's write queued. 
I think what it's missing is a check prior to the lock to see if `requestNotificationChan := make(chan Notification, 1)` has been set at all.

**Comment by skyerus** [comment]
I'm not following the concern here, each invocation of `EventStream()` will lock while setting the channel to the service's state of ongoing connections.
> I think what it's missing is a check prior to the lock to see if requestNotificationChan := make(chan Notification, 1) has been set at all.

Each `EventStream()` has its own channel, in what scenario would `requestNotificationChan` have failed to have been set?

**Comment by skyerus** [comment]
Is the concern that we're overwriting an already existing channel in the map?
The key is a pointer to the request structure, this is unique (at least until garbage collected).

**Comment by AlexsJones** [comment]
I can't see any tangible benefits to this so I defer to others.

**Comment by skyerus** [comment]
The benefit is that we're avoiding a potential race condition from writing to the same map concurrently.
